services:

  redis:
    image: redis:alpine

  django: 
    container_name: django
    build:
      context: ./djangocelery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangocelery:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./djangocelery/.env
    depends_on:
      - redis


  celery:
    container_name: celery
    build:
      context: ./djangocelery
    volumes:
      - ./djangocelery:/usr/src/app/
    env_file:
      - ./djangocelery/.env
    depends_on:
      - redis