services:

  redis:
    image: redis:alpine

  django: 
    container_name: django
    build:
      context: ./djangocelery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangocelery:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - redis


  celery:
    container_name: celery
    build:
      context: ./djangocelery
    volumes:
      - ./djangocelery:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - redis